name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
        - name: Overview
          uses: lowlighter/metrics@latest
          with:
            filename: imgs/overview.svg
            token: ${{ secrets.METRICS_TOKEN }}

        - name: Languages
          uses: lowlighter/metrics@latest
          with:
            filename: imgs/languages.svg
            plugin_languages: yes
            plugin_languages_ignored: "Jupyter Notebook"
            token: ${{ secrets.METRICS_TOKEN }}
