name: generate-and-upload-card

on:
  schedule: [{cron: "0 0 * * *"}]

  workflow_dispatch:

  # run on every push on the master branch
  push:
    branches:
    - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate github stats card
        uses: LuciNyan/pixel-profile/action@main
        with:
          outputs: |
            dist/github-stats?username=clementpoiret&screen_effect=false&theme=fuji&dithering=true&hide=avatar
            dist/github-stats-dark?username=clementpoiret&theme=crt
          github_token: ${{ secrets.GH_PAT }}

      - name: push github-stats to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: stats
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
